In [3]:
from FantAIno.data.melondy_base import MelondyBaseDataset
from FantAIno.data.melondy_classic import MelondyClassicDataset
from FantAIno.utils.data_utils import process_melondy_genre

In [4]:
test = MelondyBaseDataset()

In [5]:
embeddings_df = test.retrieve_lyrics_embeddings()

In [6]:
album_data_df = test.retrieve_tabular_album_data()

In [7]:
embeddings_df.shape, album_data_df.shape

((3120, 1538), (3420, 15))

In [8]:
FantAIno_df = album_data_df.merge(embeddings_df, on=["album_name", "artist_name"], how="left")

In [9]:
FantAIno_df.head()

                artist_name  ... embedding_dim_1535
0           Various Artists  ...          -0.008069
1               Tame Impala  ...           0.006878
2                    Harlem  ...          -0.006831
3  The Tallest Man on Earth  ...          -0.019762
4           Crystal Castles  ...          -0.000092

[5 rows x 1551 columns]

In [16]:
FantAIno_df["rating"].unique()

array([ 8,  6,  7,  9,  3,  5,  4,  2, 10,  1, -1,  0, 69])

In [17]:
FantAIno_df[FantAIno_df["rating"] == 69]

          artist_name  ... embedding_dim_1535
2317  Various Artists  ...                NaN

[1 rows x 1551 columns]

In [10]:
process_melondy_genre(FantAIno_df)

['abstract hip hop'] <class 'list'>

ValueError: malformed node or string: ['abstract hip hop']

In [12]:
test = MelondyClassicDataset()

NOTE: The number of rows with missing data: 644 out of 3420.
                                                                      genre_list  ...  embedding_dim_1535
album_name      artist_name                                                       ...
Pomegranates    Various Artists                               [abstract hip hop]  ...           -0.008069
Innerspeaker    Tame Impala                  [psychedelic rock, neo-psychedelia]  ...            0.006878
Hippies         Harlem                                 [garage rock, indie surf]  ...           -0.006831
The Wild Hunt   The Tallest Man on Earth  [contemporary folk, singer-songwriter]  ...           -0.019762
Crystal Castles Crystal Castles                               [synthpop, bitpop]  ...           -0.000092

[5 rows x 1549 columns]

KeyError: "['image_url'] not found in axis"

In [15]:
test.album_data_df

AttributeError: 'MelondyBaseDataset' object has no attribute 'album_data_df'